version: "2"
linters:
  enable:
    - containedctx
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - bodyclose
    - exhaustive
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nilnil
    - nonamedreturns
    - prealloc
    - predeclared
    - revive
    - testpackage
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gomoddirectives:
      replace-local: true
      retract-allow-no-explanation: true
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

